In [47]:
import numpy as np

a = np.array([1, 2, 3])
print("a type:", type(a)) # 確認型別
print("a:", a)
print("a記憶體位置:", a.data) # 查看記憶體位置
print("a 裡頭元素的型別:", a.dtype)
print("a * 3:", a * 3)
print("a + 2:", a + 2)
# python list
python_list = [1 ,2, 3]
print("python list:",python_list)
print("python list * 3:", python_list * 3)
b = np.array([2, 2, 0])
print("陣列運算 a + b:", a + b)
print("陣列運算 a / b:", a / b)
print("陣列運算 a * b:", a * b)
ar = np.arange(10)
print("產生0-9的數值:", ar)
print("arange(初始索引, 終點索引, 間距):", np.arange(0, 10, 2))
print("將0~10之間分成14等分(15個數字):", np.linspace(0, 10, 15))
print("反向取出:", ar[::-1])
print("取索引0-2:", ar[:3])
print("取索引4-最後一個:", ar[4:])
print("每隔1個取出元素:", ar[::2])
print("取出全部範圍:", ar[:])
snarray = np.arange(20).reshape(4, 5)
print("建立 4 * 5維的 2D陣列",snarray)
print("切出1-2列與2-3行間的 2D陣列",snarray[:2, 1:])
print("snarray[::2, :]:",snarray[::2, :])
print("snarray[:, ::2]:",snarray[:, ::2])
print("snarray[:, ::-1]:",snarray[:, ::-1])
# 建立二維陣列
c = np.array([[1, 2, 3], [4, 5, 6]])
print("c:", c)
# shape 是 ndarray 的屬性, 用顯示各維的元素數量
print("顯示c各維的元素數量:", c.shape)
print("查詢c軸數:", c.ndim) # 查詢軸數
print("將c陣列轉置:", c.T) # 將c陣列轉置
# 建立三維陣列
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print("d:", d)
print("顯示d各維的元素數量:",d.shape)
# reshape 改變其形狀
print("改變c形狀 3, 2:", c.reshape(3, 2))
print("改變c形狀 6, 1:", c.reshape(6, 1))

a type: <class 'numpy.ndarray'>
a: [1 2 3]
a記憶體位置: <memory at 0x119838460>
a 裡頭元素的型別: int64
a * 3: [3 6 9]
a + 2: [3 4 5]
python list: [1, 2, 3]
python list * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
陣列運算 a + b: [3 4 3]
陣列運算 a / b: [0.5 1.  inf]
陣列運算 a * b: [2 4 0]
產生0-9的數值: [0 1 2 3 4 5 6 7 8 9]
arange(初始索引, 終點索引, 間距): [0 2 4 6 8]
將0~10之間分成14等分(15個數字): [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
反向取出: [9 8 7 6 5 4 3 2 1 0]
取索引0-2: [0 1 2]
取索引4-最後一個: [4 5 6 7 8 9]
每隔1個取出元素: [0 2 4 6 8]
取出全部範圍: [0 1 2 3 4 5 6 7 8 9]
建立 4 * 5維的 2D陣列 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
切出1-2列與2-3行間的 2D陣列 [[1 2 3 4]
 [6 7 8 9]]
snarray[::2, :]: [[ 0  1  2  3  4]
 [10 11 12 13 14]]
snarray[:, ::2]: [[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]
snarray[:, ::-1]: [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
c: [[1 

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:16: RuntimeWarning: divide by zero encountered in true_divide
  app.launch_new_instance()


In [30]:
import time # 匯入計算時間的time模組

def calculate_time():
    a = np.random.randn(100000) # a 用 numpy 運算
    b = list(a) # 將ndarray 轉為list,  b 用傳統python 運算
    start_time = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using Numpy\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        sum_2 = sum(b)
    print("Not using Numpy\t %f sec" % (time.time() - start_time))

calculate_time()

Using Numpy	 0.059908 sec
Not using Numpy	 10.945217 sec


In [49]:
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([a, a])
print("b shape:", b.shape)
print("b:", b)
print("b sum axis 0:", b.sum(axis=0))
print("b sum axis 1:", b.sum(axis=1))
print("b sum axis 2:", b.sum(axis=2))
c = np.arange(12)
print("c:",c)
d = np.reshape(c, (3, 4))
print("c reshape 3,4 => d:",d)
d[0, 1] = 0
print(d)
print(c)

b shape: (2, 3, 2)
b: [[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]]
b sum axis 0: [[ 0  2]
 [ 4  6]
 [ 8 10]]
b sum axis 1: [[6 9]
 [6 9]]
b sum axis 2: [[1 5 9]
 [1 5 9]]
c: [ 0  1  2  3  4  5  6  7  8  9 10 11]
c reshape 3,4 => d: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  0  2  3  4  5  6  7  8  9 10 11]
