In [8]:
# 鳶尾花(iris) ML 實作範例
# 有三種鳶尾花的種類
# (山鳶尾 Iris-setona),(雜色鳶尾 Iris-versicolor),(維吉尼亞鳶尾 Iris-virginica)
import numpy as np
import pandas as pd
# Step1:資料預處理
# 讀取資料: 資料0-49山鳶尾, 50-99雜色鳶尾, 100-149維吉尼亞鳶尾
df = pd.read_csv('iris.data', header=None)
print(df)
# x 變數(花的特徵)(Sample)
x = df.iloc[0:100, [0, 1, 2, 3]].values
print(x)
# y變數(品種答案)(Label)
y = df.iloc[0:100, 4].values
print(y)
# 資料轉換
y = np.where(y=='Iris-setosa', 0, 1)
print(y)
# 資料拆分-訓練資料集, 測試資料集
x_train = np.empty((80, 4))
x_test = np.empty((20, 4))
y_train = np.empty(80)
y_test = np.empty(20)
x_train[:40], x_train[40:] = x[:40], x[50:90]
x_test[:10], x_test[10:] = x[40:50], x[90:100]
y_train[:40], y_train[40:] = y[:40], y[50:90]
y_test[:10], y_test[10:] = y[40:50], y[90:100]

# Step2:訓練神經網路
def sigmoid(x):
    return 1/(1+np.exp(-x))

def activation(x, w ,b):
    return sigmoid(np.dot(x, w) + b)

def update(x, y, w, b, eta):
    y_pred = activation(x, w, b)
    a = (y_pred - y_train) * y_pred * (1 - y_pred)
    for i in range(4):
        w[i] = w[i] - eta * 1/float(len(y)) * np.sum(a * x[:, i])
    b = b - eta * 1/float(len(y)) * np.sum(a * 1)
    return w, b
# 權重初始值預設皆為0.1
weights = np.ones(4) / 10
# b初始值預設為0.1
bias = np.ones(1)/ 10
for _ in range(9999):
    weights, bias = update(x_train, y_train, weights, bias, eta=0.1)
print('weights = ', weights, 'bias = ', bias)

# Step3:完成訓練, 測試成果
print(y_test)

print(activation(x_test, weights, bias))

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [